# coding: utf-8

"""
    Multilogin X Profile Management

    Multilogin X Profile Management API allows you to manage profiles.

    The version of the OpenAPI document: 1.0.0
    Contact: support@multilogin.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MaskingNCM(str, Enum):
    """
    MaskingNCM
    """

    """
    allowed enum values
    """
    NATURAL = 'natural'
    CUSTOM = 'custom'
    MASK = 'mask'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MaskingNCM from a JSON string"""
        return cls(json.loads(json_str))


