# coding: utf-8

"""
    Multilogin X Profile Management

    Multilogin X Profile Management API allows you to manage profiles.

    The version of the OpenAPI document: 1.0.0
    Contact: support@multilogin.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from models.MLX.fingerprint_data import FingerprintData
from models.MLX.profile_meta_flags import ProfileMetaFlags
from models.MLX.proxy import Proxy
from models.MLX.storage import Storage
from typing import Optional, Set
from typing_extensions import Self

class ProfileMetaUpdateParams(BaseModel):
    """
    ProfileMetaUpdateParams
    """ # noqa: E501
    flags: ProfileMetaFlags
    fingerprint: FingerprintData
    storage: Storage
    proxy: Optional[Proxy] = None
    custom_start_urls: Optional[Annotated[List[StrictStr], Field(max_length=5)]] = None
    custom_dns: Optional[StrictStr] = None
    extension_ids: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    __properties: ClassVar[List[str]] = ["flags", "fingerprint", "storage", "proxy", "custom_start_urls", "custom_dns", "extension_ids"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProfileMetaUpdateParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of flags
        if self.flags:
            _dict['flags'] = self.flags.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fingerprint
        if self.fingerprint:
            _dict['fingerprint'] = self.fingerprint.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage
        if self.storage:
            _dict['storage'] = self.storage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proxy
        if self.proxy:
            _dict['proxy'] = self.proxy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProfileMetaUpdateParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "flags": ProfileMetaFlags.from_dict(obj["flags"]) if obj.get("flags") is not None else None,
            "fingerprint": FingerprintData.from_dict(obj["fingerprint"]) if obj.get("fingerprint") is not None else None,
            "storage": Storage.from_dict(obj["storage"]) if obj.get("storage") is not None else None,
            "proxy": Proxy.from_dict(obj["proxy"]) if obj.get("proxy") is not None else None,
            "custom_start_urls": obj.get("custom_start_urls"),
            "custom_dns": obj.get("custom_dns"),
            "extension_ids": obj.get("extension_ids")
        })
        return _obj


