name: Test Regression

on:
    push

jobs:
    run-profile-tests:
        runs-on: ubuntu-latest
        environment: DEVELOP
        env: 
          DEV: ${{ secrets.DEV }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Download adapter
              run: |
                mkdir -p /home/runner/mlx/deps/adapter_tester
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/adapter_tester/1.0.0/linux/adapter-amd64.bin -P /home/runner/mlx/deps/adapter_tester
                cd /home/runner/mlx/deps/adapter_tester
                mv adapter-amd64.bin adapter.bin
                chmod +x adapter.bin
            
            - name: Download Launcher (Linux)
              run: |
                mkdir -p /home/runner/mlx/deps/launcher
                cd /home/runner/mlx/deps/launcher
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/CORE-1624/launcher-linux_amd64_CORE-1624.bin -P /home/runner/mlx/deps/launcher
                chmod +x launcher-linux_amd64_CORE-1624.bin  # Make Launcher executable

            - name: Start Launcher
              run: |
                cd /home/runner/mlx/deps/launcher
                ./launcher-linux_amd64_CORE-1624.bin -gw-env=dev & # Start Launcher in the background

            - name: Run Tests
              run: pytest tests/test_sign_up_flow.py

