name: Test Regression

on:
  push

jobs:
  run-profile-tests:
    runs-on: ubuntu-latest
    environment: DEVELOP
    env:
      DEV: ${{ secrets.DEV }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download Previous Index
        uses: actions/download-artifact@v3
        with:
          name: email_index
          path: ./artifact
        continue-on-error: true

      - name: Set Default Index if Absent
        run: echo "0" > ./artifact/email_index.txt || true

      - name: Set up Adapter
        run: |
          set -e
          ADAPTER_DIR=/home/runner/mlx/deps/adapter_tester
          mkdir -p $ADAPTER_DIR
          wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/adapter_tester/1.0.0/linux/adapter-amd64.bin -O $ADAPTER_DIR/adapter.bin
          chmod +x $ADAPTER_DIR/adapter.bin
          echo "1.0" > $ADAPTER_DIR/VERSION

      - name: Set up Launcher
        run: |
          set -e
          LAUNCHER_DIR=/home/runner/mlx/deps/launcher
          mkdir -p $LAUNCHER_DIR
          wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/CORE-1624/launcher-linux_amd64_CORE-1624.bin -O $LAUNCHER_DIR/launcher.bin
          chmod +x $LAUNCHER_DIR/launcher.bin

      - name: Start Launcher
        run: |
          set -e
          export ADAPTER_TESTER=1
          /home/runner/mlx/deps/launcher/launcher.bin -gw-env=dev &
          sleep 5 # Allow some time for the launcher to initialize

      - name: Run Tests
        env:
          EMAIL_INDEX_FILE: ./artifact/email_index.txt
        run: pytest tests/test_sign_up_flow.py
      
      - name: Upload Updated Index
        uses: actions/upload-artifact@v3
        with:
          name: email_index
          path: ./artifact/email_index.txt