name: Test Regression

on:
    push

jobs:
    run-profile-tests:
        runs-on: ubuntu-latest
        environment: DEVELOP
        env: 
          DEV: ${{ secrets.DEV }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Download Launcher (Linux)
              run: |
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/latest-build/launcher-linux_amd64.bin  
                chmod +x launcher-linux_amd64.bin  # Make Launcher executable
            
            - name: Download Core (Linux)
              run: |
                mkdir /home/runner/mlx/deps/mimic
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/browser-mimic/131.7/browser-mimic_linux-amd64.tar.gz -P /home/runner/mlx/deps/mimic
                cd /home/runner/mlx/deps/mimic
                tar xvzf browser-mimic_linux-amd64.tar.gz

            - name: Start Launcher
              run: |
                cd ~
                ./launcher-linux_amd64.bin -gw-env=dev &  # Start Launcher in the background

            - name: Run Tests
              run: pytest tests/test_sign_up_flow.py

