name: Test Regression

on:
    push

jobs:
    run-profile-tests:
        runs-on: ubuntu-latest
        environment: DEVELOP
        env: 
          DEV: ${{ secrets.DEV }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Download Launcher (Linux)
              run: |
                wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/latest-build/launcher-linux_amd64.bin  
                chmod +x launcher-linux_amd64.bin  # Make Launcher executable

            - name: Create YAML configuration file
              run: |
                cat <<EOF > launcher.yaml
                LogLevel: debug
                LogConsole: true
                GwEnv: dev
                EOF
            
            - name: Create directory
              run: |
                mkdir -p /home/runner/mlx/configs

            - name: Move the config file to mlx/configs
              run: |
                cp launcher.yaml /home/runner/mlx/configs

            - name: Start Launcher
              run: |
                ./launcher-linux_amd64.bin &  # Start Launcher in the background

            - name: Run Tests
              run: pytest tests/test_sign_up_flow.py

