name: Test Regression

on:
  push

jobs:
  run-profile-tests:
    runs-on: ubuntu-latest
    environment: DEVELOP
    env:
      DEV: ${{ secrets.DEV }}
      EMAIL_INDEX: ${{ vars.EMAIL_INDEX }}
      EMAIL: ${{ vars.EMAIL}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Adapter
        run: |
          set -e
          ADAPTER_DIR=/home/runner/mlx/deps/adapter_tester
          mkdir -p $ADAPTER_DIR
          wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/adapter_tester/1.0.0/linux/adapter-amd64.bin -O $ADAPTER_DIR/adapter.bin
          chmod +x $ADAPTER_DIR/adapter.bin
          echo "1.0" > $ADAPTER_DIR/VERSION

      - name: Set up Launcher
        run: |
          set -e
          LAUNCHER_DIR=/home/runner/mlx/deps/launcher
          mkdir -p $LAUNCHER_DIR
          wget https://ml000x-dev-dists.s3.eu-north-1.amazonaws.com/launcher-mlx/CORE-1624/launcher-linux_amd64_CORE-1624.bin -O $LAUNCHER_DIR/launcher.bin
          chmod +x $LAUNCHER_DIR/launcher.bin

      - name: Start Launcher
        run: |
          export ADAPTER_TESTER=1
          /home/runner/mlx/deps/launcher/launcher.bin -gw-env=dev &
          sleep 5 # Allow some time for the launcher to initialize

      - name: Run Tests
        run: |
          echo "Current email: $EMAIL"
          echo "Current email index: $EMAIL_INDEX"
          pytest tests/test_sign_up_flow.py
      
      - name: Update Email Index
        run: |
          index=${{ vars.EMAIL_INDEX }} 
          NEW_INDEX=$((index + 1))
          echo "Incremented index: $NEW_INDEX"
          echo "EMAIL_INDEX=$NEW_INDEX" >> $GITHUB_ENV
          echo "Updating EMAIL_INDEX"
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Andr-NG/mlx-testing/environments/DEVELOP/variables/EMAIL_INDEX \
            -d "{\"name\":\"EMAIL_INDEX\",\"value\":\"$NEW_INDEX\"}"